#!/bin/sh
#
# Condition the environment for Mu development, using binaries and
# libraries in a sandboxed directory.

export SANDBOX_NAME='Mu'
export MU_ROOT=/Users/r/Projects/Mu/usr

# GMOCK / GTEST live in the packages dir
export GMOCK_DIR=/Users/r/Projects/Mu/Packages/gmock-1.7.0
export GTEST_DIR=${GMOCK_DIR}/gtest

# ================================================================
# set the paths
export PATH=${MU_ROOT}/bin:${PATH}
export DYLD_LIBRARY_PATH=${MU_ROOT}/lib

# ================================================================
# set the prompt so we know we're in the sandbox
export PS1='${SANDBOX_NAME}[\w]$ '
# ... and away we go

exec /bin/bash

