#!/bin/sh
#
# Condition the environment for Mu development, using binaries and
# libraries in a sandboxed directory.

export SANDBOX_NAME='Mu'
export MU_ROOT=/Users/r/Projects/Mu/usr

# ================================================================
# set the path
export PATH=${MU_ROOT}/bin:${PATH}
export DYLD_LIBRARY_PATH=${MU_ROOT}/lib

# ================================================================
# set the prompt so we know we're in the sandbox
export PS1='${SANDBOX_NAME}[\w]$ '
# ... and away we go

exec /bin/bash

