#!/bin/sh
export CSV_FILE=source_periods.csv

echo file_name, measured_period, estimated_period > ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/A#4.wav - 94 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/A#5.wav - 47 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/A4.wav - 100 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/A4a.wav - 100 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/A5.wav - 50 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/B4.wav - 89 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/B4a.wav - 89 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/B5.wav - 44 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/C#4.wav - 159 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/C#5.wav - 80 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/C4.wav - 169 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/C5.wav - 84 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/D#4.wav - 141 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/D#5.wav - 71 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/D4.wav - 150 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/D5.wav - 75 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/E4.wav - 133 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/E5.wav - 66 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/F#4.wav - 119 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/F#5.wav - 60 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/F4.wav - 126 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/F4a.wav - 126 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/F5.wav - 63 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/F5a.wav - 63 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/G#4.wav - 106 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/G#4a.wav - 106 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/G#4b.wav - 106 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/G#5.wav - 53 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/G4.wav - 113 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckFinger/G5.wav - 56 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/A#4.wav - 94 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/A4.wav - 100 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/A4a.wav - 100 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/A5.wav - 50 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/A5a.wav - 50 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/A5b.wav - 50 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/B4.wav - 89 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C#4.wav - 159 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C#5.wav - 80 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C#5a.wav - 80 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C#5b.wav - 80 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C4.wav - 169 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C5.wav - 84 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/C5a.wav - 84 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/D#4.wav - 142 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/D#5.wav - 71 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/D4.wav - 150 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/D5.wav - 75 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/E4.wav - 133 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/E5.wav - 67 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/F#4.wav - 119 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/F#5.wav - 60 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/F4.wav - 126 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/F5.wav - 63 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/G#4.wav - 106 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/G#5.wav - 53 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/G4.wav - 113 >> ${CSV_FILE}
./psi_file_generator /Users/r/Projects/Musics/TNVM/sources/PluckThumb/G5.wav - 56 >> ${CSV_FILE}
