/*
 * MapStream lets the user examine and (optionally) modify individual
 * frames generated by a source stream.  After fetching the data from
 * the source, MapStream calls a user-supplied method with the current
 * tick, stkFrames object, index into the stkFrames object and a
 * reference to the Player object.
 *
 * The user-supplied method may modify samples in place.  It can do
 * other things as well, such as print information about individual
 * frames and/or halt playback under certain conditions.
 */
#ifndef MU_MAP_STREAM_H
#define MU_MAP_STREAM_H

#include "mu.h"
#include "single_source_stream.h"

namespace mu {

  typedef void (*MapStreamCallback)( stk::StkFrames& buffer, 
                                     Tick tick, 
                                     Player& player,
                                     Tick frame_index );
  
  class MapStream : public SingleSourceStream {
  public:

    MapStream();
    ~MapStream( void );
    std::string getClassName() { return "MapStream"; }

    MapStream& step(stk::StkFrames& buffer, Tick tick, Player &player);

    // needed(??) so setSource() returns a MapStream and not a SingleSourceStream
    MapStream& setSource(Stream *source) { source_ = source; return *this; }

    MapStreamCallback getCallback() const;
    MapStream& setCallback(MapStreamCallback callback);

  protected:
    MapStreamCallback callback_;

  };                            // class MapStream

  inline MapStream::MapStream() {
    TRACE("MapStream::MapStream()\n");
  }

  inline MapStreamCallback MapStream::getCallback() const { return callback_; }
  inline MapStream& MapStream::setCallback(MapStreamCallback callback) {
    TRACE("MapStream::setCallback()\n");
    callback_ = callback; return *this;
  }

}                               // namespace mu

#endif
